apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/projectcalico/calico/v3.32.0/manifests/calico-policy-only.yaml

patches:
  - path: patch-calico-node.yaml
  - path: patch-kube-controllers.yaml
