apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-vm-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-vm-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
  - kind: ServiceAccount
    name: calico-vm-agent
    namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: calico-vm-agent-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: calico-vm-agent
type: kubernetes.io/service-account-token
