apiVersion: v1
kind: Node
metadata:
  name: hep-0605-0534-legacy-01
  labels:
    kubernetes.io/hostname: hep-0605-0534-legacy-01
    kubernetes.io/os: linux
    lab.calico.io/non-cluster-host: "true"
spec:
  unschedulable: true
  taints:
    - key: lab.calico.io/non-cluster-host
      value: "true"
      effect: NoSchedule
