apiVersion: crd.projectcalico.org/v1
kind: HostEndpoint
metadata:
  name: hep-0605-0534-legacy-01-eth0
  labels:
    endpoint_role: legacy-web
    host_name: hep-0605-0534-legacy-01
    policy_profile: baseline
    platform: vm
spec:
  node: hep-0605-0534-legacy-01
  interfaceName: eth0
  expectedIPs:
    - 10.70.20.20
